"""add scheduled_at to tasks

Revision ID: 037e0d7694d7
Revises: f4a821ca2608
Create Date: 2026-05-10 04:38:40.067039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037e0d7694d7'
down_revision: Union[str, Sequence[str], None] = 'f4a821ca2608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'scheduled_at')
    # ### end Alembic commands ###
