"""upgrade status table

Revision ID: 610aa77b00aa
Revises: d6ec75c3ebb7
Create Date: 2026-05-07 14:37:19.967649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610aa77b00aa'
down_revision: Union[str, Sequence[str], None] = 'd6ec75c3ebb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
