"""add taskscheduled to schema

Revision ID: 85411db5d35e
Revises: 3e56e56b0e10
Create Date: 2026-05-10 05:27:58.878467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85411db5d35e'
down_revision: Union[str, Sequence[str], None] = '3e56e56b0e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE status ADD VALUE IF NOT EXISTS 'SCHEDULED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
